In [1]:
import numpy as np

In [4]:
a=np.array([[2,3,5],[5,8,6],[11,22,33]])
b=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [5]:
a-b

array([[ 1,  3,  5],
       [ 5,  7,  6],
       [11, 22, 32]])

In [6]:
a*b

array([[ 2,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 33]])

In [7]:
#This is the matrix multiplication, called dot product in numpy
np.dot(a,b)


array([[ 2,  3,  5],
       [ 5,  8,  6],
       [11, 22, 33]])

In [9]:
b*8

array([[8, 0, 0],
       [0, 8, 0],
       [0, 0, 8]])